<a href="https://colab.research.google.com/github/Vigneshthanga/258-Deep-Learning/blob/master/Assignment-0/numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basics of Numpy Arrays

##1. Numpy array Initialization

In [0]:
import numpy as np
np.random.seed(5)

#randint first argument produce a random number within 10
x1 = np.random.randint(10, size=5)
x2 = np.random.randint(10, size=(5, 5))
x3 = np.random.randint(10, size=(5, 5, 5))
print(x3)

[[[4 4 9 3 2]
  [4 6 9 3 3]
  [2 1 5 7 4]
  [3 1 7 3 1]
  [9 5 7 0 9]]

 [[6 0 5 2 8]
  [6 8 0 5 2]
  [0 7 7 6 0]
  [0 8 5 5 9]
  [6 4 5 2 8]]

 [[8 1 6 3 4]
  [1 8 0 2 2]
  [4 1 6 3 4]
  [3 1 4 2 3]
  [4 9 4 0 6]]

 [[6 9 2 9 3]
  [0 8 8 9 7]
  [4 8 6 8 0]
  [5 3 4 0 2]
  [2 1 1 7 1]]

 [[7 2 6 3 6]
  [8 0 9 1 9]
  [0 8 7 7 9]
  [4 1 4 2 1]
  [7 5 4 2 2]]]


##2. Numpy Attributes

In [0]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (5, 5, 5)
x3 size:  125


##3. Indexing Numpy Arrays

In [0]:
print(x3[4,4,4]) #last element in the corner

2


##4. Slicing two rows and three columns

In [0]:
print(x2[:2, :3])

[[8 4 7]
 [7 1 5]]


##5. Broadcasting

In [0]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
print(a + b)

[5 6 7]
